export const QUERY_KEY_CONSTANTS = {
  GET_THREADS_LIST: ["GET_THREADS_LIST"],
  GET_CATEGORIES_LIST: ["GET_CATEGORIES_LIST"],
  GET_FOLLOWING_STATUS: ["GET_FOLLOWING_STATUS"],
  GET_USER_INFO: ["GET_USER_INFO"],
  GET_LIKE_STATUS: ["GET_LIKE_STATUS"],
  GET_COMMENTS:["GET_COMMENTS"],
  GET_COMMENTS_REPLIES:["GET_COMMENTS_REPLIES:"],
  GET_COMMENTS_LIKE_STATUS:[" GET_COMMENTS_LIKE_STATUS"],
  GET_COMMENTS_REPLY_LIKE_STATUS:[" GET_COMMENTS_REPLY_LIKE_STATUS"]
};
