export const QUERY_KEY_CONSTANTS = {
  GET_THREADS_LIST: ["GET_THREADS_LIST"],
  GET_CATEGORIES_LIST: ["GET_CATEGORIES_LIST"],
  GET_FOLLOWING_STATUS: [" GET_FOLLOWING_STATUS"],
  GET_USER_INFO: [" GET_USER_INFO"],
};
